/*
 * SPDX-FileCopyrightText: 2026 OPPO
 * SPDX-License-Identifier: Apache-2.0
 */

import type { AutotestContext, TestResult } from './types'

/**
 * End-to-end coverage for the PDF text-selection engine
 * (`resources/pdfjs/app/text-selection.js`).
 *
 * The acceptance axiom, inherited from the reference project's adversarial
 * analysis and the reason this suite exists at all:
 *
 *     visible highlight === Selection.toString() === clipboard text === expected
 *
 * A test that only checks `Selection.toString()` is a smoke test. What makes
 * selection *correct* is that the three agree — a caret-mapping bug typically
 * produces a selection that reads right in one of them and wrong in another.
 *
 * Paired unit coverage lives in `test/unittest/pdf-text-selection-*.test.mts`,
 * which pins the pure decisions (what is one selectable unit, which
 * annotations block). This file proves the wiring: that those decisions
 * actually reach a real drag over a real rendered PDF.
 *
 * Fixture: `test/autotest/fixtures/pdf-text-selection/onward-textsel.pdf`,
 * generated by `pdf-text-selection-fixture-builder.mjs`. Regenerate with
 * `--write`, verify with `--check`.
 */

const TEST_PDF_FILENAME = '__autotest_pdf_textsel.pdf'
const TEST_MARKER_FILENAME = '__autotest_pdf_textsel_marker.txt'

const FIXTURE_REL_PATH = 'test/autotest/fixtures/pdf-text-selection/onward-textsel.pdf'

// Must match FIXTURE_TEXT in the builder. Duplicated rather than imported
// because the autotest bundle cannot reach into test/ at runtime; the builder's
// --check mode is what keeps the fixture itself honest.
const TEXT = {
  ligatureLine: 'The office of efficient design',
  selectLine: 'SELECTME uniqueword ENDMARK',
  secondLine: 'Second line continues here',
  visibleOverHidden: 'VISIBLETEXT',
  hiddenUnderVisible: 'HIDDENTEXT',
  blockedByAnnotation: 'BLOCKEDTEXT'
}

// Boolean-correctness assertions repeat N times and require all to pass
// (CLAUDE.md timing-sensitive autotest rule). A single successful drag proves
// nothing about a path that races text-layer rendering.
const DRAG_TRIALS = 5

interface ViewerTextSelectionApi {
  page(pageNumber: number): Element | null
  findSpan(pageNumber: number, needle: string): Element | null
  dragBetween(
    pageNumber: number,
    fromNeedle: string,
    toNeedle?: string,
    options?: { inset?: number; steps?: number }
  ): string | null
  subRect(
    pageNumber: number,
    spanNeedle: string,
    subText: string
  ): { left: number; right: number; top: number; bottom: number; height: number } | null
  dragSubstrings(
    pageNumber: number,
    spanNeedle: string,
    fromSub: string,
    toSub?: string
  ): string | null
  dragIntoMiddleOf(
    pageNumber: number,
    spanNeedle: string,
    fromSub: string,
    targetSub: string
  ): string | null
  dragPoints(
    from: { x: number; y: number },
    to: { x: number; y: number },
    steps?: number
  ): string
  selectionText(): string
  clear(): void
  overlayRectCount(): number
  textLayerContent(pageNumber: number): string
  invisibleSpanCount(pageNumber: number): number
  annotationRoles(pageNumber: number): Record<string, string>
  simulateCopy(): string | null
}

function joinPath(base: string, child: string): string {
  const trimmed = base.replace(/[\\/]+$/, '')
  return `${trimmed}/${child}`
}

function platformBuildCopyCommand(srcRelPath: string, destFilename: string, rootPath: string): string {
  if (window.electronAPI.platform === 'win32') {
    const src = `${rootPath}\\${srcRelPath.replace(/\//g, '\\')}`
    return `powershell -Command "Copy-Item -LiteralPath '${src}' -Destination '${destFilename}' -Force"`
  }
  const src = `${rootPath}/${srcRelPath}`
  return `cp "${src}" "${destFilename}"`
}

function platformBuildWriteMarkerCommand(filename: string, content: string): string {
  if (window.electronAPI.platform === 'win32') {
    return `powershell -Command "Set-Content -LiteralPath '${filename}' -Value '${content}' -NoNewline"`
  }
  return `printf '%s' '${content}' > '${filename}'`
}

function platformBuildDeleteCommand(filenames: string[]): string {
  if (window.electronAPI.platform === 'win32') {
    return filenames.map(f => `if (Test-Path '${f}') { Remove-Item -Force '${f}' }`).join('; ')
  }
  return filenames.map(f => `rm -f '${f}'`).join(' && ')
}

export async function testPdfTextSelection(ctx: AutotestContext): Promise<TestResult[]> {
  const { log, sleep, waitFor, assert, cancelled, terminalId, rootPath } = ctx
  const results: TestResult[] = []
  const record = (name: string, ok: boolean, detail?: Record<string, unknown>) => {
    assert(name, ok, detail)
    results.push({ name, ok, detail })
  }

  const getApi = () => window.__onwardProjectEditorDebug

  const termExec = async (command: string, label: string, waitMs = 1200) => {
    await window.electronAPI.terminal.write(terminalId, `${command}\r`)
    await sleep(waitMs)
    log(`exec:${label}`, { command: command.length > 120 ? `${command.slice(0, 120)}…` : command })
  }

  /**
   * The selection engine's listeners are bound to the iframe's own window, and
   * synthetic events built in this realm do not reliably reach them. So the
   * test drives the engine through the viewer's in-realm probe object, the
   * same approach the existing keyboard-forwarding assertions already use.
   */
  const getViewerApi = (): ViewerTextSelectionApi | null => {
    const iframe = document.querySelector('.project-editor-pdf-reader-iframe') as HTMLIFrameElement | null
    const frameWindow = iframe?.contentWindow as (Window & {
      __onwardPdfTest?: { textSelection?: ViewerTextSelectionApi }
    }) | null | undefined
    return frameWindow?.__onwardPdfTest?.textSelection ?? null
  }

  log('pdf-text-selection:start', { rootPath })

  await termExec(
    platformBuildWriteMarkerCommand(TEST_MARKER_FILENAME, 'onward-autotest-marker'),
    'marker:create'
  )
  await termExec(
    platformBuildCopyCommand(FIXTURE_REL_PATH, TEST_PDF_FILENAME, rootPath),
    'pdf:copy',
    1200
  )

  const pdfPath = joinPath(rootPath, TEST_PDF_FILENAME)
  const markerPath = joinPath(rootPath, TEST_MARKER_FILENAME)

  if (cancelled()) return results

  // ---------- open + wait for a rendered text layer ----------

  await getApi()?.openFileByPathAsUser?.(pdfPath)
  const readerVisible = await waitFor(
    'pdf-textsel-reader-visible',
    () => getApi()?.isPdfReaderVisible?.() === true,
    10000
  )
  record('pdf-textsel-reader-visible', readerVisible, { filename: TEST_PDF_FILENAME })

  // The probe object only exists once the viewer script has run; the text
  // layer only exists once pdf.js has rendered page 1. Wait for the text
  // itself rather than a timer, so a slow host stretches the wait instead of
  // producing a flaky failure.
  const textLayerReady = await waitFor(
    'pdf-textsel-text-layer-rendered',
    () => {
      const api = getViewerApi()
      return Boolean(api && api.findSpan(1, 'SELECTME'))
    },
    20000,
    150
  )
  record('pdf-textsel-text-layer-rendered', textLayerReady, {
    content: getViewerApi()?.textLayerContent(1)?.slice(0, 160) ?? null
  })

  if (!textLayerReady) {
    // Every remaining assertion depends on a rendered text layer; continuing
    // would produce a wall of derived failures that hide the real one.
    log('pdf-text-selection:abort', { reason: 'text layer never rendered' })
    await termExec(platformBuildDeleteCommand([TEST_PDF_FILENAME, TEST_MARKER_FILENAME]), 'cleanup')
    return results
  }

  const api = getViewerApi()!

  // ---------- the four-way agreement, repeated ----------

  {
    // pdf.js emits one span per `Tj`, so a whole line is a single span and a
    // span-edge-to-span-edge drag would always return the whole line — green
    // no matter how broken caret mapping is. Every drag below therefore
    // targets a SUBSTRING's measured rect, so the assertion actually depends
    // on the engine putting the caret where the pointer is.
    const trials: Array<{ selected: string | null; reported: string; copied: string | null }> = []
    for (let i = 0; i < DRAG_TRIALS; i += 1) {
      api.clear()
      await sleep(60)
      const selected = api.dragSubstrings(1, 'SELECTME', 'SELECTME')
      const reported = api.selectionText()
      const copied = api.simulateCopy()
      trials.push({ selected, reported, copied })
      await sleep(60)
    }
    // The acceptance axiom: what the engine selected, what the DOM reports,
    // and what a copy would place on the clipboard must be one string.
    const allAgree = trials.every(
      t => Boolean(t.selected) && t.selected === t.reported && t.reported === t.copied
    )
    record('pdf-textsel-selection-copy-agreement-5x', allAgree, { trials })

    // …and the drag must stop at the word, not run to the end of the line.
    const allExact = trials.every(t => (t.reported || '').trim() === 'SELECTME')
    record('pdf-textsel-single-word-bounded-5x', allExact, {
      texts: trials.map(t => t.reported)
    })
  }

  // ---------- ligature integrity on a real render ----------

  {
    // The unit tests prove `ffi` is one segment. This proves that segmentation
    // actually governs a real drag: aim the caret at the horizontal MIDDLE of
    // the ffi glyph and the engine must snap to a cluster boundary. In
    // "office" (o | ffi | c | e) that means the selection ends either before
    // the cluster ("o") or after it ("offi") — "off" would be a torn glyph.
    const trials: string[] = []
    for (let i = 0; i < DRAG_TRIALS; i += 1) {
      api.clear()
      await sleep(60)
      trials.push(api.dragIntoMiddleOf(1, 'office', 'office', 'ffi') ?? '')
      await sleep(60)
    }
    const snapped = trials.every(text => {
      const value = (text || '').trim()
      return value === 'o' || value === 'offi'
    })
    record('pdf-textsel-ligature-snaps-to-cluster-5x', snapped, { texts: trials })
  }

  // ---------- multi-word drag inside a line ----------

  {
    api.clear()
    await sleep(80)
    // Starts mid-line, so a selection that ran to either span edge fails.
    const text = api.dragSubstrings(1, 'SELECTME', 'uniqueword', 'ENDMARK') ?? ''
    const copied = api.simulateCopy()
    record(
      'pdf-textsel-multi-word-drag',
      text.trim() === 'uniqueword ENDMARK' && text === copied,
      { text, copied }
    )
  }

  // ---------- hidden text must not be selectable ----------

  {
    const layerText = api.textLayerContent(1)
    const invisibleLeft = api.invisibleSpanCount(1)

    // The fixture draws HIDDENTEXT with Tr 3 (paints nothing) directly under a
    // visible VISIBLETEXT. That is how a scanned page's OCR layer and how a
    // copy-protection watermark are both encoded. It must be gone from the
    // text layer entirely.
    record(
      'pdf-textsel-covered-hidden-text-removed',
      !layerText.includes(TEXT.hiddenUnderVisible) && invisibleLeft === 0,
      { invisibleLeft, layerText: layerText.slice(0, 200) }
    )

    api.clear()
    await sleep(80)
    const dragged = api.dragBetween(1, TEXT.visibleOverHidden) ?? ''
    const copied = api.simulateCopy() ?? ''
    record(
      'pdf-textsel-hidden-text-not-copied',
      !dragged.includes(TEXT.hiddenUnderVisible) && !copied.includes(TEXT.hiddenUnderVisible),
      { dragged, copied }
    )
  }

  // ---------- blocking annotation ----------

  {
    const roles = api.annotationRoles(1)
    const roleValues = Object.values(roles)
    record(
      'pdf-textsel-annotation-classified-blocking',
      roleValues.includes('blocking'),
      { roles }
    )

    // Dragging across text that a FreeText annotation covers must not yield
    // that text. This is the leak class the reference project reproduced:
    // the user sees an annotation, drags over it, and silently copies the PDF
    // text hidden underneath.
    api.clear()
    await sleep(80)
    const dragged = api.dragBetween(1, TEXT.blockedByAnnotation) ?? ''
    const copied = api.simulateCopy() ?? ''
    record(
      'pdf-textsel-blocked-text-not-selectable',
      !dragged.includes(TEXT.blockedByAnnotation) && !(copied || '').includes(TEXT.blockedByAnnotation),
      { dragged, copied }
    )
  }

  // ---------- click clears the selection ----------

  {
    api.clear()
    await sleep(60)
    api.dragSubstrings(1, 'SELECTME', 'SELECTME')
    const before = api.selectionText()
    const span = api.findSpan(1, 'Second') as HTMLElement | null
    if (span) {
      const rect = span.getBoundingClientRect()
      // A plain click (no travel) on the page must drop the selection.
      api.dragPoints(
        { x: rect.left + 4, y: rect.top + rect.height / 2 },
        { x: rect.left + 4, y: rect.top + rect.height / 2 },
        2
      )
    }
    await sleep(120)
    const after = api.selectionText()
    record('pdf-textsel-click-clears-selection', Boolean(before) && after === '', { before, after })
  }

  // ---------- selection survives a zoom change without leaking overlay ----------

  {
    api.clear()
    await sleep(60)
    api.dragBetween(1, 'SELECTME', 'ENDMARK')
    const iframe = document.querySelector('.project-editor-pdf-reader-iframe') as HTMLIFrameElement | null
    const zoomSelect = iframe?.contentDocument?.getElementById('zoomSelect') as HTMLSelectElement | null
    if (zoomSelect) {
      zoomSelect.value = '1.5'
      zoomSelect.dispatchEvent(new Event('change', { bubbles: true }))
    }
    await sleep(500)
    // Zoom invalidates every cached rect, so the engine drops the selection
    // rather than leaving stale overlay rects painted at the old geometry.
    record(
      'pdf-textsel-zoom-clears-stale-overlay',
      api.overlayRectCount() === 0 && api.selectionText() === '',
      { overlayRects: api.overlayRectCount(), selection: api.selectionText() }
    )
  }

  // ---------- the engine survives a document switch ----------

  {
    await getApi()?.openFileByPath(markerPath)
    const cleared = await waitFor(
      'pdf-textsel-reader-cleared',
      () => getApi()?.isPdfReaderVisible?.() === false,
      5000
    )
    record('pdf-textsel-reader-cleared', cleared)

    await getApi()?.openFileByPath(pdfPath)
    const reopened = await waitFor(
      'pdf-textsel-selection-works-after-reopen',
      () => {
        const next = getViewerApi()
        return Boolean(next && next.findSpan(1, 'SELECTME'))
      },
      20000,
      150
    )
    let textAfterReopen = ''
    if (reopened) {
      const next = getViewerApi()!
      next.clear()
      await sleep(120)
      textAfterReopen = next.dragSubstrings(1, 'SELECTME', 'SELECTME') ?? ''
    }
    record(
      'pdf-textsel-selection-works-after-reopen',
      reopened && textAfterReopen.trim() === 'SELECTME',
      { reopened, textAfterReopen }
    )
  }

  await termExec(platformBuildDeleteCommand([TEST_PDF_FILENAME, TEST_MARKER_FILENAME]), 'cleanup')
  log('pdf-text-selection:done', { assertions: results.length })
  return results
}
